### ISSUE TITLE
so it doesn't work right now?

### ISSUE THREAD

**Issue by brianboyer** [nprapps/elections14#1138]
I click "COME ON IN" and i dont get a countdown, and the stack is empty.

**Comment by onyxfish** [comment]
I'm not seeing this? Did you fix it already?

**Comment by onyxfish** [comment]
Or maybe I fixed it when I pushed earlier?

**Comment by onyxfish** [comment]
Closing this until I hear otherwise.

**Comment by brianboyer** [comment]
Its still not working on my machine. But I'm probably missing a step to bootstrap. Could use a hand.

**Comment by brianboyer** [comment]
i killed the slides that got bootstrapped in and readded new slides and it seems to work. no idea whats up but i'm the only person having this problem. hrmmmmmm.
